name: Deploy Website

on: [push]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - run: yarn build
      - name: install yarn
        run: sudo apt update && sudo apt install yarn
      - name: Build React App
        run: yarn build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build bootcamp_react_talha.surge.sh --token ${{ secrets.SURGE_TOKEN }}
	
